# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local

services:
###########################
# Setup the Nginx container
###########################
    nginx:
        container_name: ycf-nginx-local
        image: daocloud.io/library/nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        container_name: ycf-php70-local
        build: ./docker/php/7.0
        expose:
            - 9000
        volumes:
            - /home/project:/var/www/html:rw
            # - /media/kcloze/8685937c-af42-4319-aa9b-bb123ccd18ba/data/www:/var/www/html:rw

###########################
# Setup the Database (MySQL) container
###########################
    # mysql:
    #     image: mysql:latest
    #     expose:
    #         - 3306
    #     volumes:
    #         - database_data:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: secret
    #         MYSQL_DATABASE: project
    #         MYSQL_USER: project
    #         MYSQL_PASSWORD: project
